name: Build and Publish

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest

    env:
      Solution_Name: Serilog.Sinks.WPF.sln
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build
      run: msbuild Serilog.Sinks.WPF/Serilog.Sinks.WPF.sln --configuration Release
