name: Build Package
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore Serilog.Sinks.WPF\Serilog.Sinks.WPF.sln
 
    - name: Build and Publish Package
      run: msbuild Serilog.Sinks.WPF\Serilog.Sinks.WPF.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
     
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
          PROJECT_FILE_PATH: Serilog.Sinks.WPF\Serilog.Sinks.WPF.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
